scrape_configs:
-   job_name: 'prometheus'
    static_configs:
        - targets:
            - 'localhost:9091'
    basic_auth:
        username: "{{ pillar.monitor.prometheus.web.username }}"
        password: "{{ pillar.monitor.prometheus.web.password }}"

-   job_name: 'node_exporter'
    static_configs:
        - targets: 
            - 'localhost:9100'

-   job_name: 'aws-ec2'
    ec2_sd_configs:
        -   region: us-east-1
            access_key: {{ pillar.monitor.prometheus.ec2_sd_configs.access_key }}
            secret_key: {{ pillar.monitor.prometheus.ec2_sd_configs.secret_key }}
            port: 9100

rule_files:
-   /etc/prometheus.rules-config.yml

alerting:
    alertmanagers:
        - static_configs:
            - targets:
                - localhost:9095
