apiVersion: v1alpha1
sts-region: us-east-1
discovery:
    exportedTagsOnMetrics:
        route53:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
    jobs:
      - type: AWS/Route53
        regions:
          - us-east-1
        dimensionNameRequirements:
            - HealthCheckId
        metrics:
          - name: HealthCheckPercentageHealthy
            statistics:
                - Average
            period: 60 # seconds
            length: 300 # seconds, 5 minutes
