apiVersion: v1alpha1
sts-region: us-east-1
discovery:
    exportedTagsOnMetrics:
        route53:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
    jobs:
        - type: AWS/Route53
          regions:
              - us-east-1
          dimensionNameRequirements:
              - HealthCheckId
        # lsh@2023-09-12: temporary, until the tags on the healthchecks start coming through:
        # - https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/1145
          customTags:
              - key: Environment
                value: prod
          metrics:
              - name: HealthCheckPercentageHealthy
                statistics:
                    - Average
                period: 60
                length: 600

        - type: AWS/ELB
          regions:
              - us-east-1
          dimensionNamerequirements:
              - LoadBalancerName
          period: 1
          length: 600
          metrics:
              - name: Latency
                statistics:
                    - Average
                period: 10
              - name: RequestCount
                statistics:
                    - Sum
              - name: HTTPCode_Backend_2XX
                statistics:
                    - Sum
              - name: HTTPCode_Backend_5XX
                statistics:
                    - Sum

