apiVersion: v1alpha1
sts-region: us-east-1
discovery:
    exportedTagsOnMetrics:
        route53:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
        elb:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
        ec2:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment

    jobs:
        - type: AWS/Route53
          regions:
              - us-east-1
          dimensionNameRequirements:
              - HealthCheckId
        # lsh@2023-09-12: temporary, until the tags on the healthchecks start coming through:
        # - https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/1145
          customTags:
              - key: Environment
                value: prod
          metrics:
              - name: HealthCheckPercentageHealthy
                statistics:
                    - Average
                period: 60  # seconds
                length: 600 # seconds

        - type: AWS/ELB
          regions:
              - us-east-1
          dimensionNameRequirements:
              - LoadBalancerName
          # "Statistic period in seconds"
          period: 300   # seconds
          # "How far back to request data for in seconds"
          length: 300   # seconds
          metrics:
              # "[HTTP listener] The total time elapsed, in seconds, from the time the load balancer sent the request to a registered instance until the instance started to send the response headers."
              - name: Latency
                statistics:
                    - Average
              - name: RequestCount
                statistics:
                    - Sum
              - name: HTTPCode_Backend_2XX
                statistics:
                    - Sum
              - name: HTTPCode_Backend_5XX
                statistics:
                    - Sum

        - type: AWS/EC2
          regions:
              - us-east-1
          dimensionNameRequirements:
            - InstanceId
          # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html#status-check-metrics
          metrics:
            - name: StatusCheckFailed_System # AWS problems, they'll typically send an email.
              statistics:
                - Maximum
            - name: StatusCheckFailed_Instance # our problem, they'll typically not do anything
              statistics:
                - Maximum

