apiVersion: v1alpha1
sts-region: us-east-1
discovery:
    exportedTagsOnMetrics:
        route53:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
        elb:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
        alb:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment
        ec2:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment

        rds:
            - Name          # typically the url to be queried
            - Project       # journal, crm, etc
            - Environment   # prod, etc
            - name
            - project
            - environment

    jobs:
        - type: AWS/Route53
          regions:
              - us-east-1
          dimensionNameRequirements:
              - HealthCheckId
        # lsh@2023-09-12: temporary, until the tags on the healthchecks start coming through:
        # - https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/1145
          customTags:
              - key: Environment
                value: prod
          metrics:
              - name: HealthCheckPercentageHealthy
                statistics:
                    - Average
                period: 60  # seconds
                length: 600 # seconds

        - type: AWS/ELB
          regions:
              - us-east-1
          dimensionNameRequirements:
              - LoadBalancerName
          # "Statistic period in seconds"
          period: 60   # seconds
          # "How far back to request data for in seconds"
          length: 300   # five mins
          metrics:
              # "[HTTP listener] The total time elapsed, in seconds, from the time the load balancer sent the request to a registered instance until the instance started to send the response headers."
              - name: Latency
                # todo: consider setting period from 300 seconds to 60 seconds
                statistics:
                    - Average
              - name: RequestCount
                statistics:
                    - Sum
              - name: HTTPCode_Backend_2XX
                statistics:
                    - Sum
              - name: HTTPCode_Backend_5XX
                statistics:
                    - Sum
              - name: UnHealthyHostCount
                statistics:
                    - Maximum
                period: 60
                length: 3600 # one hour

        - type: AWS/ApplicationELB
          regions:
              - us-east-1
          dimensionNameRequirements:
              - LoadBalancer
          metrics:
              - name: RequestCount
                statistics:
                    - Sum
              - name: HTTPCode_Target_2XX_Count
                statistics:
                    - Sum
              - name: HTTPCode_Target_5XX_Count
                statistics:
                    - Sum

        - type: AWS/ApplicationELB
          regions:
              - us-east-1
          dimensionNameRequirements:
              - TargetGroup
              - LoadBalancer
          period: 60
          length: 3600
          metrics:
              - name: UnHealthyHostCount
                statistics:
                    - Maximum

        - type: AWS/EC2
          regions:
              - us-east-1
          dimensionNameRequirements:
            - InstanceId
          # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html#status-check-metrics
          metrics:
            - name: StatusCheckFailed_System # AWS problems, they'll typically send an email.
              statistics:
                - Maximum
            - name: StatusCheckFailed_Instance # our problem, they'll typically not do anything
              statistics:
                - Maximum

        - type: AWS/RDS
          regions:
              - us-east-1
          dimensionNameRequirements:
              - DBInstanceIdentifier
          metrics:
              - name: CPUUtilization
                statistics:
                    - Average
                period: 5
                length: 60

              - name: FreeableMemory
                statistics:
                    - Average
                period: 5
                length: 60

              - name: FreeStorageSpace
                statistics:
                    - Minimum
                period: 5
                length: 60

              - name: NetworkReceiveThroughput
                statistics:
                    - Average
                period: 5
                length: 60

              - name: NetworkTransmitThroughput
                statistics:
                    - Average
                period: 5
                length: 60

              - name: DatabaseConnections
                statistics:
                    - Maximum
                period: 5
                length: 60

static:
    - name: ses
      namespace: AWS/SES
      regions:
        - us-east-1
      metrics:
        - name: Send
          statistics:
            - Sum
          period: 60
          length: 600
          nilToZero: true
        - name: Delivery
          statistics:
            - Sum
          period: 60
          length: 600
          nilToZero: true
        # not present, it should be? https://docs.aws.amazon.com/ses/latest/dg/event-publishing-retrieving-cloudwatch.html
        #- name: Reject
        #  statistics:
        #    - Sum
        #  nilToZero: true
        - name: Bounce
          statistics:
            - Sum
          period: 60
          length: 600
          nilToZero: true
        - name: Reputation.BounceRate # "Bounce" - also not present
          statistics:
            - Sum
          period: 60
          length: 600
          nilToZero: true
        - name: Reputation.ComplaintRate # "Complaint" -- also not present
          statistics:
            - Sum
          period: 60
          length: 600
          nilToZero: true

