{% if salt['elife.cfg']('cfn.outputs.DomainName') %}
tls_server_config:
    cert_file: /etc/certificates/certificate.crt
    key_file: /etc/certificates/fullchain.pem
{% endif %}

# Usernames and passwords required to connect to Prometheus.
# Passwords are hashed with bcrypt: https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
basic_auth_users:
    {{ pillar.monitor.prometheus.web.username }}: {{ pillar.monitor.prometheus.web.password }}
