scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets:
                - "localhost:9093"
      basic_auth:
          username: "{{ pillar.monitor.prometheus.web.username }}"
          password: "{{ pillar.monitor.prometheus.web.password }}"

    - job_name: "aws-ec2" # node-exporter
      ec2_sd_configs:
          - region: us-east-1
            access_key: "{{ pillar.monitor.prometheus.ec2_sd_configs.access_key }}"
            secret_key: "{{ pillar.monitor.prometheus.ec2_sd_configs.secret_key }}"
            port: 9100
      relabel_configs:
          # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config
          - source_labels: ["__meta_ec2_tag_Name"]      # annotations--continuumtest--1
            target_label: "ec2_name"
          - source_labels: ["__meta_ec2_tag_Project"]   # annotations
            target_label: "project"
          - source_labels: ["__meta_ec2_tag_Cluster"]   # annotations--continuumtest, aka 'stackname'
            target_label: "project_instance"
          - source_labels: ["__meta_ec2_tag_Environment"] # continuumtest
            target_label: "env"
          - source_labels: ["__meta_ec2_tag_Node"] # 1
            target_label: "ec2_node"

    - job_name: "caddy"
      ec2_sd_configs:
          - region: us-east-1
            access_key: "{{ pillar.monitor.prometheus.ec2_sd_configs.access_key }}"
            secret_key: "{{ pillar.monitor.prometheus.ec2_sd_configs.secret_key }}"
            port: 1234
            filters:
              - name: tag:Project
                values:
                  - bioprotocol
                  - api-gateway
                  - search
                  - redirects
                  - api-dummy
                  - personalised-covers
                  - observer
                  - elife-metrics
                  - elife-dashboard
                  - recommendations
                  - annotations
                  - elife-alfred
                  - digests
                  - pattern-library
                  #- lax
                  #- journal
                  #- foo
                  #- bar
      relabel_configs:
          # https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config
          - source_labels: ["__meta_ec2_tag_Name"]      # annotations--continuumtest--1
            target_label: "ec2_name"
          - source_labels: ["__meta_ec2_tag_Project"]   # annotations
            target_label: "project"
          - source_labels: ["__meta_ec2_tag_Cluster"]   # annotations--continuumtest, aka 'stackname'
            target_label: "project_instance"
          - source_labels: ["__meta_ec2_tag_Environment"] # continuumtest
            target_label: "env"
          - source_labels: ["__meta_ec2_tag_Node"] # 1
            target_label: "ec2_node"

    - job_name: "yace"
      static_configs:
        - targets:
            - "localhost:9097"
      relabel_configs:
        - source_labels: ["tag_environment"]
          target_label: "env"
        - source_labels: ["tag_project"]
          target_label: "project"
        # lsh@2023-09-12: temporary, until the 'environment' tag starts coming through
        # - https://github.com/nerdswords/yet-another-cloudwatch-exporter/issues/1145
        - source_labels: ["custom_tag_environment"]
          target_label: "env"

rule_files:
    - /etc/prometheus.rules-config.yml

alerting:
    alertmanagers:
        - static_configs:
              - targets:
                    - localhost:9093
          basic_auth:
              username: "{{ pillar.monitor.prometheus.web.username }}"
              password: "{{ pillar.monitor.prometheus.web.password }}"

