# https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/

groups:
    - name: "production policy"
      rules:
          # https://grafana.com/blog/2021/04/01/you-should-know-about...-these-useful-prometheus-alerting-rules/#the-up-query
          # matches old "host not reporting" alert
          - alert: ProductionHostNotReporting
            expr: up{ec2_env="prod"} == 0
            for: 5m
            labels:
                severity: critical
            annotations:
                # "A production host is not reporting: lax--prod--3"
                summary: "A production host is not reporting: {{ $labels.ec2_name }}"


    - name: "continuumtest policy"
      rules:
          - alert: ContinuumtestHostNotReporting
            expr: up{ec2_env="continuumtest"} == 0
            for: 5m
            labels:
                severity: warning
            annotations:
                # "A continuumtest host is not reporting: lax--prod--3"
                summary: "A continuumtest host is not reporting: {{ $labels.ec2_name }}"

    - name: "common policy"
      rules:
          - alert: DiskUsageHigh
            expr: (100 - ((node_filesystem_avail_bytes{mountpoint=~"/|/ext"} * 100) / node_filesystem_size_bytes)) > 70
            for: 20m
            labels:
                severity: warning
            annotations:
                # "Disk usage ('/') is over 70%: lax--prod--3"
                summary: "Disk usage ('{{ $labels.mountpoint }}') is over 70%: {{ $labels.ec2_name }}"

          - alert: DiskUsageVeryHigh
            expr: (100 - ((node_filesystem_avail_bytes{mountpoint=~"/|/ext"} * 100) / node_filesystem_size_bytes)) > 80
            for: 5m
            labels:
                severity: critical
            annotations:
                # "Disk usage ('/ext') is over 80%: lax--prod--3"
                summary: "Disk usage ('{{ $labels.mountpoint }}') is over 80%: {{ $labels.ec2_name }}"

          # https://grafana.com/blog/2021/04/01/you-should-know-about...-these-useful-prometheus-alerting-rules/#alerts-for-use-and-red
          # Please add ignored mount points in node_exporter parameters like
          # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
          # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
          - alert: HostDiskWillFillIn24Hours
            expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: Host disk will fill in 24 hours (instance {{ $labels.instance }})
                description: "Filesystem is predicted to run out of space within the next 24 hours at current write rate\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

