apiVersion: v1alpha1
sts-region: us-east-1
{% if not pillar.monitor.healthcheck_list %}
static: []
{% else %}
static:
{% for healthcheck in pillar.monitor.healthcheck_list %}
  - namespace: AWS/Route53
    name: {{ healthcheck.name }}
    regions:
      - us-east-1
    metrics:
      - name: HealthCheckPercentageHealthy
        statistics:
        - Average
        period: 60 # seconds
        length: 300 # seconds, 5 minutes
    dimensions:
      - name: HealthCheckId
        value: {{ healthcheck.id }}
{% endfor %}
{% endif %}
